/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/plantas/scene.gltf -t -r public
Author: AllQuad (https://sketchfab.com/AllQuad)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/indoor-plants-pack-35-b0819769d34a496e82d674b5668be5c1
Title: Indoor Plants Pack 35
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    BOSTON_FERN_BOSTON_FERN_Mat_0: THREE.Mesh
    DARK_POT_CERAMIC_BASE_01_POT_DARK_CERAMIC_BASE_Mat_0: THREE.Mesh
    ZAMIA_FURFURACEA_ZAMIA_FURFURACEA_Mat_0: THREE.Mesh
    DARK_POT_CERAMIC_BASE_02_POT_DARK_CERAMIC_BASE_Mat_0: THREE.Mesh
    STRELITZIA_STRELITZIA_Mat_0: THREE.Mesh
    DARK_POT_CERAMIC_BASE_04_POT_DARK_CERAMIC_BASE_Mat_0: THREE.Mesh
    FICUS_LYRATA_Ficus_Lyrata_Mat_0: THREE.Mesh
    DARK_POT_CERAMIC_BASE_03_POT_DARK_CERAMIC_BASE_Mat_0: THREE.Mesh
  }
  materials: {
    BOSTON_FERN_Mat: THREE.MeshStandardMaterial
    POT_DARK_CERAMIC_BASE_Mat: THREE.MeshStandardMaterial
    ZAMIA_FURFURACEA_Mat: THREE.MeshStandardMaterial
    STRELITZIA_Mat: THREE.MeshStandardMaterial
    Ficus_Lyrata_Mat: THREE.MeshStandardMaterial
  }
}

export default function Plantas(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/plantas/scene.gltf') as GLTFResult
  return (
    <group {...props} dispose={null} position={[0, 0, -5]}>
      <group scale={0.08}>
        <group position={[-56.95, 0.2, -17.11]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.DARK_POT_CERAMIC_BASE_01_POT_DARK_CERAMIC_BASE_Mat_0.geometry} material={materials.POT_DARK_CERAMIC_BASE_Mat} />
          <mesh geometry={nodes.BOSTON_FERN_BOSTON_FERN_Mat_0.geometry} material={materials.BOSTON_FERN_Mat} />
        </group>
        <group position={[22.73, -1.33, -6.95]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.DARK_POT_CERAMIC_BASE_02_POT_DARK_CERAMIC_BASE_Mat_0.geometry} material={materials.POT_DARK_CERAMIC_BASE_Mat} />
          <mesh geometry={nodes.ZAMIA_FURFURACEA_ZAMIA_FURFURACEA_Mat_0.geometry} material={materials.ZAMIA_FURFURACEA_Mat} />
        </group>
        <group position={[0, 0.2, 63.76]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.DARK_POT_CERAMIC_BASE_04_POT_DARK_CERAMIC_BASE_Mat_0.geometry} material={materials.POT_DARK_CERAMIC_BASE_Mat} />
          <mesh geometry={nodes.STRELITZIA_STRELITZIA_Mat_0.geometry} material={materials.STRELITZIA_Mat} />
        </group>
        <group position={[-33.94, 0.2, 70.34]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.DARK_POT_CERAMIC_BASE_03_POT_DARK_CERAMIC_BASE_Mat_0.geometry} material={materials.POT_DARK_CERAMIC_BASE_Mat} />
          <mesh geometry={nodes.FICUS_LYRATA_Ficus_Lyrata_Mat_0.geometry} material={materials.Ficus_Lyrata_Mat} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/plantas/scene.gltf')
