/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/SILLAS/SILLASSOLIDAS.gltf -t -r public
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube032: THREE.Mesh
  }
  materials: {
    ASIENTO: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/SILLAS/SILLASSOLIDAS.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube032.geometry} material={materials.ASIENTO} position={[-17.82, -0.06, -19.9]} rotation={[0, 0.16, 0]} />
    </group>
  )
}

useGLTF.preload('/SILLAS/SILLASSOLIDAS.gltf')
