/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/TABLE/scene.gltf -t -r public
Author: Francesco Coldesina (https://sketchfab.com/topfrank2013)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/table-set-6eab0c3c7ed74124ac7481394d9395c8
Title: Table Set
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
    Object_3: THREE.Mesh
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
    Object_6: THREE.Mesh
    Object_7: THREE.Mesh
    Object_8: THREE.Mesh
  }
  materials: {
    Material__167: THREE.MeshStandardMaterial
    PIatto01: THREE.MeshStandardMaterial
    TVUnik_Baked01: THREE.MeshStandardMaterial
  }
}

export default function Table(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/TABLE/scene.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}
      scale={[0.25, 0.25, 0.25]}
      receiveShadow
      castShadow
    >
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Material__167} receiveShadow
      castShadow />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Material__167} receiveShadow
      castShadow/>
        <mesh geometry={nodes.Object_4.geometry} material={materials.Material__167}receiveShadow
      castShadow />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Material__167} receiveShadow
      castShadow/>
        <mesh geometry={nodes.Object_6.geometry} material={materials.PIatto01} receiveShadow
      castShadow/>
        <mesh geometry={nodes.Object_7.geometry} material={materials.TVUnik_Baked01} receiveShadow
      castShadow/>
        <mesh geometry={nodes.Object_8.geometry} material={materials.TVUnik_Baked01}receiveShadow
      castShadow />
      </group>
    </group>
  )
}

useGLTF.preload('/TABLE/scene.gltf')
