/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/ELIAS/ELIAS.gltf -t -r public
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ELIAS_1: THREE.Mesh
    ELIAS_2: THREE.Mesh
    ELIAS_3: THREE.Mesh
    ELIAS_4: THREE.Mesh
  }
  materials: {
    ELIAS: THREE.MeshStandardMaterial
    ELIAS1: THREE.MeshStandardMaterial
    ELIAS2: THREE.MeshStandardMaterial
    ELIAS3: THREE.MeshStandardMaterial
  }
}

export default function ELIAS(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/ELIAS/ELIAS.gltf') as GLTFResult
  return (
    <group {...props} dispose={null} scale={0.4}>
      <group position={[13, 5, 5]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.ELIAS_1.geometry} material={materials.ELIAS} />
        <mesh geometry={nodes.ELIAS_2.geometry} material={materials.ELIAS1} />
        <mesh geometry={nodes.ELIAS_3.geometry} material={materials.ELIAS2} />
        <mesh geometry={nodes.ELIAS_4.geometry} material={materials.ELIAS3} />
      </group>
    </group>
  )
}

useGLTF.preload('/ELIAS/ELIAS.gltf')
