/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/FORT4k/modular_fort_01_4k.gltf -t -r public
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane007: THREE.Mesh
    Plane007_1: THREE.Mesh
    Cylinder: THREE.Mesh
    Cylinder_1: THREE.Mesh
    Plane006: THREE.Mesh
    Plane006_1: THREE.Mesh
    Plane032: THREE.Mesh
    Plane032_1: THREE.Mesh
    Plane011: THREE.Mesh
    Plane011_1: THREE.Mesh
    Plane013: THREE.Mesh
    Plane013_1: THREE.Mesh
    Plane009: THREE.Mesh
    Plane009_1: THREE.Mesh
    Plane016: THREE.Mesh
    Plane016_1: THREE.Mesh
    Plane012: THREE.Mesh
    Plane012_1: THREE.Mesh
    Plane015: THREE.Mesh
    Plane015_1: THREE.Mesh
    Plane017: THREE.Mesh
    Plane017_1: THREE.Mesh
    Plane010: THREE.Mesh
    Plane010_1: THREE.Mesh
    Plane019: THREE.Mesh
    Plane019_1: THREE.Mesh
    Plane002: THREE.Mesh
    Plane002_1: THREE.Mesh
    Plane005: THREE.Mesh
    Plane005_1: THREE.Mesh
    Plane004: THREE.Mesh
    Plane004_1: THREE.Mesh
    Plane004_2: THREE.Mesh
    Plane020: THREE.Mesh
    Plane020_1: THREE.Mesh
    Plane028: THREE.Mesh
    Plane028_1: THREE.Mesh
    Plane031: THREE.Mesh
    Plane031_1: THREE.Mesh
    Plane026: THREE.Mesh
    Plane026_1: THREE.Mesh
    Plane008: THREE.Mesh
    Plane008_1: THREE.Mesh
    Plane014: THREE.Mesh
    Plane014_1: THREE.Mesh
  }
  materials: {
    modular_fort_01_wall_1: THREE.MeshStandardMaterial
    modular_fort_01_trim_1: THREE.MeshStandardMaterial
    modular_fort_01_plaster_1: THREE.MeshStandardMaterial
  }
}

export default function Fort4k(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/FORT4k/modular_fort_01_4k.gltf') as GLTFResult
  return (
    <group {...props} dispose={null} >
      <group position={[10.06, 0, 19.83]}>
        <mesh geometry={nodes.Plane007.geometry} material={materials.modular_fort_01_wall_1} />
        <mesh geometry={nodes.Plane007_1.geometry} material={materials.modular_fort_01_trim_1} />
      </group>
      <group position={[40.12, 0, -26.03]}>
        <mesh geometry={nodes.Cylinder.geometry} material={materials.modular_fort_01_wall_1} />
        <mesh geometry={nodes.Cylinder_1.geometry} material={materials.modular_fort_01_trim_1} />
      </group>
      <group position={[10, 0, -34]}>
        <mesh geometry={nodes.Plane006.geometry} material={materials.modular_fort_01_wall_1} />
        <mesh geometry={nodes.Plane006_1.geometry} material={materials.modular_fort_01_trim_1} />
      </group>
      <group position={[48.38, 0, 20.22]}>
        <mesh geometry={nodes.Plane032.geometry} material={materials.modular_fort_01_wall_1} />
        <mesh geometry={nodes.Plane032_1.geometry} material={materials.modular_fort_01_trim_1} />
      </group>
      <group position={[18.38, 0, 8.53]}>
        <mesh geometry={nodes.Plane011.geometry} material={materials.modular_fort_01_wall_1} />
        <mesh geometry={nodes.Plane011_1.geometry} material={materials.modular_fort_01_trim_1} />
      </group>
      <group position={[23.22, 0, 20.37]}>
        <mesh geometry={nodes.Plane013.geometry} material={materials.modular_fort_01_wall_1} />
        <mesh geometry={nodes.Plane013_1.geometry} material={materials.modular_fort_01_trim_1} />
      </group>
      <group position={[19, 0, -14]}>
        <mesh geometry={nodes.Plane009.geometry} material={materials.modular_fort_01_wall_1} />
        <mesh geometry={nodes.Plane009_1.geometry} material={materials.modular_fort_01_trim_1} />
      </group>
      <group position={[38.59, 0, 35.37]}>
        <mesh geometry={nodes.Plane016.geometry} material={materials.modular_fort_01_wall_1} />
        <mesh geometry={nodes.Plane016_1.geometry} material={materials.modular_fort_01_trim_1} />
      </group>
      <group position={[10.61, 0, 30.19]}>
        <mesh geometry={nodes.Plane012.geometry} material={materials.modular_fort_01_wall_1} />
        <mesh geometry={nodes.Plane012_1.geometry} material={materials.modular_fort_01_trim_1} />
      </group>
      <group position={[10, 0, -14]}>
        <mesh geometry={nodes.Plane015.geometry} material={materials.modular_fort_01_wall_1} />
        <mesh geometry={nodes.Plane015_1.geometry} material={materials.modular_fort_01_trim_1} />
      </group>
      <group position={[31.54, 0, 7.2]}>
        <mesh geometry={nodes.Plane017.geometry} material={materials.modular_fort_01_wall_1} />
        <mesh geometry={nodes.Plane017_1.geometry} material={materials.modular_fort_01_trim_1} />
      </group>
      <group position={[36.38, 0, 20.03]}>
        <mesh geometry={nodes.Plane010.geometry} material={materials.modular_fort_01_wall_1} />
        <mesh geometry={nodes.Plane010_1.geometry} material={materials.modular_fort_01_trim_1} />
      </group>
      <group position={[10.19, 0, 7.2]}>
        <mesh geometry={nodes.Plane019.geometry} material={materials.modular_fort_01_wall_1} />
        <mesh geometry={nodes.Plane019_1.geometry} material={materials.modular_fort_01_trim_1} />
      </group>
      <group position={[24.66, 0, 35.53]}>
        <mesh geometry={nodes.Plane002.geometry} material={materials.modular_fort_01_wall_1} />
        <mesh geometry={nodes.Plane002_1.geometry} material={materials.modular_fort_01_trim_1} />
      </group>
      <group position={[40.76, 0, 7.2]}>
        <mesh geometry={nodes.Plane005.geometry} material={materials.modular_fort_01_wall_1} />
        <mesh geometry={nodes.Plane005_1.geometry} material={materials.modular_fort_01_trim_1} />
      </group>
      <group position={[35, 0, -14]}>
        <mesh geometry={nodes.Plane004.geometry} material={materials.modular_fort_01_wall_1} />
        <mesh geometry={nodes.Plane004_1.geometry} material={materials.modular_fort_01_trim_1} />
        <mesh geometry={nodes.Plane004_2.geometry} material={materials.modular_fort_01_plaster_1} />
      </group>
      <group position={[38.59, 0, 32.82]}>
        <mesh geometry={nodes.Plane020.geometry} material={materials.modular_fort_01_wall_1} />
        <mesh geometry={nodes.Plane020_1.geometry} material={materials.modular_fort_01_trim_1} />
      </group>
      <group position={[45, 0, -14]}>
        <mesh geometry={nodes.Plane028.geometry} material={materials.modular_fort_01_wall_1} />
        <mesh geometry={nodes.Plane028_1.geometry} material={materials.modular_fort_01_trim_1} />
      </group>
      <group position={[13.15, 0, 30.19]}>
        <mesh geometry={nodes.Plane031.geometry} material={materials.modular_fort_01_wall_1} />
        <mesh geometry={nodes.Plane031_1.geometry} material={materials.modular_fort_01_trim_1} />
      </group>
      <group position={[26, 0, -14]}>
        <mesh geometry={nodes.Plane026.geometry} material={materials.modular_fort_01_wall_1} />
        <mesh geometry={nodes.Plane026_1.geometry} material={materials.modular_fort_01_trim_1} />
      </group>
      <group position={[19, 0, -34]}>
        <mesh geometry={nodes.Plane008.geometry} material={materials.modular_fort_01_wall_1} />
        <mesh geometry={nodes.Plane008_1.geometry} material={materials.modular_fort_01_trim_1} />
      </group>
      <group position={[49.55, 0, 9.56]}>
        <mesh geometry={nodes.Plane014.geometry} material={materials.modular_fort_01_wall_1} />
        <mesh geometry={nodes.Plane014_1.geometry} material={materials.modular_fort_01_trim_1} />
      </group>
    </group>
  )
}

useGLTF.preload('/FORT4k/modular_fort_01_4k.gltf')
