/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/LADDER/ladder_sectioned_01_4k.gltf -t -r public
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ladder_section_01: THREE.Mesh
    ladder_section_02: THREE.Mesh
    ladder_section_03: THREE.Mesh
    ladder_ribbon: THREE.Mesh
  }
  materials: {
    ladder_sectioned_01: THREE.MeshStandardMaterial
  }
}

export default function Ladder(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/LADDER/ladder_sectioned_01_4k.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.ladder_section_01.geometry} material={materials.ladder_sectioned_01} position={[0.03, 0, -0.02]} />
      <mesh geometry={nodes.ladder_section_02.geometry} material={materials.ladder_sectioned_01} position={[0.03, 0, 0.02]} />
      <mesh geometry={nodes.ladder_section_03.geometry} material={materials.ladder_sectioned_01} position={[0.03, 0, 0.06]} />
      <mesh geometry={nodes.ladder_ribbon.geometry} material={materials.ladder_sectioned_01} position={[0.03, 0, -0.05]} />
    </group>
  )
}

useGLTF.preload('/LADDER/ladder_sectioned_01_4k.gltf')
