/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/SILLA_MESA/outdoor_table_chair_set_01_4k.gltf -t -r public
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    outdoor_table_chair_set_01_chair_01: THREE.Mesh
    outdoor_table_chair_set_01_table: THREE.Mesh
    outdoor_table_chair_set_01_chair_02: THREE.Mesh
  }
  materials: {
    outdoor_table_chair_set_01_chair: THREE.MeshStandardMaterial
    outdoor_table_chair_set_01_table: THREE.MeshStandardMaterial
  }
}

export default function Silla_Mesa(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/SILLA_MESA/outdoor_table_chair_set_01_4k.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.outdoor_table_chair_set_01_chair_01.geometry} material={materials.outdoor_table_chair_set_01_chair} rotation={[0, 0.24, 0]} />
      <mesh geometry={nodes.outdoor_table_chair_set_01_table.geometry} material={materials.outdoor_table_chair_set_01_table} />
      <mesh geometry={nodes.outdoor_table_chair_set_01_chair_02.geometry} material={materials.outdoor_table_chair_set_01_chair} rotation={[0, 0.27, 0]} />
    </group>
  )
}

useGLTF.preload('/SILLA_MESA/outdoor_table_chair_set_01_4k.gltf')
