/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/SOFA2/sofa_02_4k.gltf -t -r public
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    sofa_02_Base: THREE.Mesh
    sofa_02_Seat: THREE.Mesh
  }
  materials: {
    sofa_02: THREE.MeshStandardMaterial
  }
}

export default function Sofa2(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/SOFA2/sofa_02_4k.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.sofa_02_Base.geometry} material={materials.sofa_02} position={[0, 0, 0.03]} />
      <mesh geometry={nodes.sofa_02_Seat.geometry} material={materials.sofa_02} position={[0, 0, 0.03]} />
    </group>
  )
}

useGLTF.preload('/SOFA2/sofa_02_4k.gltf')
