/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/TREE/jacaranda_tree_4k.gltf -t -r public
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    jacaranda_tree_trunk: THREE.Mesh
    jacaranda_tree_branches: THREE.Mesh
    Plane5958: THREE.Mesh
    Plane5958_1: THREE.Mesh
  }
  materials: {
    jacaranda_tree_trunk: THREE.MeshStandardMaterial
    jacaranda_tree_branches: THREE.MeshStandardMaterial
    jacaranda_tree_leaves: THREE.MeshStandardMaterial
  }
}

export default function Tree(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/TREE/jacaranda_tree_4k.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.jacaranda_tree_trunk.geometry} material={materials.jacaranda_tree_trunk} />
      <mesh geometry={nodes.jacaranda_tree_branches.geometry} material={materials.jacaranda_tree_branches} />
      <mesh geometry={nodes.Plane5958.geometry} material={materials.jacaranda_tree_branches} />
      <mesh geometry={nodes.Plane5958_1.geometry} material={materials.jacaranda_tree_leaves} />
    </group>
  )
}

useGLTF.preload('/TREE/jacaranda_tree_4k.gltf')
